from django.db import models


class Event(models.Model):
    event_id = models.CharField(max_length=100)
    investigation_type = models.CharField(max_length=100, null=True, blank=True)
    accident_number = models.CharField(max_length=100, primary_key=True, unique=True)
    event_date = models.DateField()
    location = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    airport_code = models.CharField(max_length=10, null=True, blank=True)
    airport_name = models.CharField(max_length=100, null=True, blank=True)
    injury_severity = models.CharField(max_length=100)
    aircraft_damage = models.CharField(max_length=100, null=True, blank=True)
    aircraft_category = models.CharField(max_length=100, null=True, blank=True)
    registration_number = models.CharField(max_length=100, null=True, blank=True)
    make = models.CharField(max_length=100, null=True, blank=True)
    model = models.CharField(max_length=100, null=True, blank=True)
    amateur_built = models.CharField(max_length=100, null=True, blank=True)
    number_of_engines = models.IntegerField(null=True, blank=True)
    engine_type = models.CharField(max_length=100, null=True, blank=True)
    far_description = models.CharField(max_length=100, null=True, blank=True)
    schedule = models.CharField(max_length=100, null=True, blank=True)
    purpose_of_flight = models.CharField(max_length=100, null=True, blank=True)
    air_carrier = models.CharField(max_length=100, null=True, blank=True)
    total_fatal_injuries = models.IntegerField(null=True, blank=True)
    total_serious_injuries = models.IntegerField(null=True, blank=True)
    total_minor_injuries = models.IntegerField(null=True, blank=True)
    total_uninjured = models.IntegerField(null=True, blank=True)
    weather_condition = models.CharField(max_length=100, null=True, blank=True)
    broad_phase_of_flight = models.CharField(max_length=100, null=True, blank=True)
    report_status = models.CharField(max_length=100, null=True, blank=True)
    publication_date = models.DateField(null=True, blank=True)
